name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Cache Fetched Data
        id: cache-fetched-restore
        uses: actions/cache@v4
        with:
          path: |
            src/lib/data
            src/lib/translations
            static/data
          key: ${{ runner.os }}-fetched-${{ hashFiles('./GAMEINFO.md') }}

      - name: Fetch Data
        if: steps.cache-fetched-restore.outputs.cache-hit != 'true'
        run: bun run cli fetch

      - name: Build app
        run: npm run build

      - name: Copy static assets
        run: cp -r static build/

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build